// Generated by split-command-controller.mjs
import type { CommandController } from './index';

export async function handleRecoveryCherryPick(
  this: CommandController,
  arg?: unknown
): Promise<void> {
  await this.recovery?.cherryPick(arg);
}
