// Generated by split-command-controller.mjs
import type { CommandController } from './index';

export async function handleRecoveryCreateBranch(
  this: CommandController,
  arg?: unknown
): Promise<void> {
  await this.recovery?.createBranch(arg);
}
