// Generated by split-command-controller.mjs
import type { CommandController } from './index';

export async function handleRecoveryCancelScan(this: CommandController): Promise<void> {
  await this.recovery?.cancelScan();
}
