// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import * as vscode from 'vscode';

export async function handleRecoveryOpen(this: CommandController): Promise<void> {
  if (!this.recovery) {
    void vscode.window.showWarningMessage(
      'Recovery Center is unavailable in the current workspace.'
    );
    return;
  }
  await this.recovery.open();
}
