// Generated by split-command-controller.mjs
import type { CommandController } from './index';
import * as path from 'path';
import * as vscode from 'vscode';

interface RepositoryQuickPickItem extends vscode.QuickPickItem {
  readonly rootUri: vscode.Uri;
}

export async function handleRepositorySelect(this: CommandController): Promise<void> {
  const repositories = await this.git.getRepositorySelectionRoots();
  const workspaceRoot = this.git.context.rootPath;
  const items: RepositoryQuickPickItem[] = repositories.map((rootUri) => {
    const isWorkspaceRoot = this.git.samePath(rootUri.fsPath, workspaceRoot);
    const relativePath = isWorkspaceRoot ? '' : path.relative(workspaceRoot, rootUri.fsPath);
    const isActive = this.git.samePath(rootUri.fsPath, this.git.rootPath);
    return {
      label: isWorkspaceRoot ? 'Workspace repository' : relativePath,
      description: isActive
        ? 'Active repository'
        : isWorkspaceRoot
          ? 'Workspace root'
          : 'Submodule',
      detail: rootUri.fsPath,
      rootUri
    };
  });

  const selected = await vscode.window.showQuickPick(items, {
    placeHolder: 'Select the repository used by VS Code Git Client',
    matchOnDescription: true,
    matchOnDetail: true
  });
  if (selected && this.selectRepository) {
    await this.selectRepository(selected.rootUri);
  }
}
