// Generated by split-command-controller.mjs
import type { CommandController } from './index';

export async function handleRecoveryRefreshReflog(
  this: CommandController,
  arg?: unknown
): Promise<void> {
  await this.recovery?.refreshReflog(arg);
}
