// Generated by split-command-controller.mjs
import type { CommandController } from './index';

export async function handleRecoveryPreview(this: CommandController, arg?: unknown): Promise<void> {
  await this.recovery?.preview(arg);
}
