// Generated by split-command-controller.mjs
import type { CommandController } from './index';

export async function handleRecoveryToggleAllRefs(this: CommandController): Promise<void> {
  await this.recovery?.toggleAllRefs();
}
