// Generated by split-command-controller.mjs
import type { CommandController } from './index';

export async function handleRecoveryOpenWorktree(
  this: CommandController,
  arg?: unknown
): Promise<void> {
  await this.recovery?.openWorktree(arg);
}
