// Generated by split-class.mjs
import type { GitService } from './index';

export async function createBranch(this: GitService, name: string, base?: string): Promise<void> {
  const branchName = name.trim();
  const validationError = await this.validateBranchName(branchName);
  if (validationError) {
    throw new Error(validationError);
  }

  const repository = await this.getVsCodeRepository();
  if (repository) {
    this.logger.info(`vscode.git createBranch ${branchName}${base ? ` ${base}` : ''}`);
    await repository.createBranch(branchName, false, base);
    return;
  }
  const args = ['branch', branchName];
  if (base) {
    args.push(base);
  }
  await this.runGit(args);
}
