// Generated by split-class.mjs
import type { GitService } from './index';
import {
  parseReflogEntries,
  REFERENCE_LOG_FIELD_SEPARATOR,
  REFERENCE_LOG_RECORD_SEPARATOR
} from '../../recovery/reflogParser';
import { RecoveryReflogEntry } from '../../recovery/recoveryTypes';

export async function getRecoveryReflogEntries(
  this: GitService,
  limit: number,
  includeAllRefs = false
): Promise<RecoveryReflogEntry[]> {
  const format = [
    `%gD${REFERENCE_LOG_FIELD_SEPARATOR}`,
    `%H${REFERENCE_LOG_FIELD_SEPARATOR}`,
    `%gs${REFERENCE_LOG_RECORD_SEPARATOR}`
  ].join('');

  const result = await this.runGit([
    'reflog',
    'show',
    ...(includeAllRefs ? ['--all'] : ['HEAD']),
    '--date=unix',
    '--no-abbrev',
    `--format=${format}`,
    '-n',
    String(limit)
  ]);

  return parseReflogEntries(result.stdout);
}
