// Generated by split-class.mjs
import type { GitService } from './index';
import { CommitFileChange } from '../../types';
import { parseNameStatusZ } from '../gitParsing';

export async function getRecoverySnapshotFiles(
  this: GitService,
  fromOid: string,
  toRef: string
): Promise<CommitFileChange[]> {
  const result = await this.runGit([
    'diff',
    '--name-status',
    '-z',
    '--find-renames',
    fromOid,
    toRef
  ]);
  return parseNameStatusZ(result.stdout);
}
