// Generated by split-class.mjs
import type { GitService } from './index';
import * as path from 'path';
import * as vscode from 'vscode';
import { parseSubmoduleStatus } from '../submoduleParsing';

/**
 * Returns the workspace repository and every initialized nested submodule.
 * This deliberately discovers repositories through Git rather than relying on
 * VS Code's SCM selection model, which does not always expose submodules.
 */
export async function getRepositorySelectionRoots(this: GitService): Promise<vscode.Uri[]> {
  const workspaceRoot = this.context.rootPath;
  const roots = new Map<string, vscode.Uri>();
  const addRoot = (rootPath: string): void => {
    const normalized = path.normalize(rootPath);
    roots.set(normalized, vscode.Uri.file(rootPath));
  };

  addRoot(workspaceRoot);

  try {
    const status = await this.runGitAt(workspaceRoot, ['submodule', 'status', '--recursive']);
    const submodules = parseSubmoduleStatus(status.stdout).filter(
      (submodule) => !submodule.isUninitialized && submodule.path.length > 0
    );

    await Promise.all(
      submodules.map(async (submodule) => {
        const requestedPath = path.resolve(workspaceRoot, submodule.path);
        if (!isWithinWorkspace(workspaceRoot, requestedPath)) {
          return;
        }
        try {
          const result = await this.runGitAt(requestedPath, ['rev-parse', '--show-toplevel']);
          const rootPath = result.stdout.trim();
          if (rootPath && isWithinWorkspace(workspaceRoot, rootPath)) {
            addRoot(rootPath);
          }
        } catch {
          // A stale or inaccessible submodule should not prevent choosing
          // another repository.
        }
      })
    );
  } catch {
    // The workspace repository remains available when it has no submodules or
    // Git cannot enumerate them.
  }

  return [...roots.values()].sort((left, right) => {
    if (this.samePath(left.fsPath, workspaceRoot)) {
      return -1;
    }
    if (this.samePath(right.fsPath, workspaceRoot)) {
      return 1;
    }
    return left.fsPath.localeCompare(right.fsPath);
  });
}

function isWithinWorkspace(workspaceRoot: string, candidatePath: string): boolean {
  const relative = path.relative(workspaceRoot, candidatePath);
  return (
    relative !== '' &&
    relative !== '..' &&
    !relative.startsWith('..' + path.sep) &&
    !path.isAbsolute(relative)
  );
}
