// Generated by split-class.mjs
import type { GitService } from './index';
import * as vscode from 'vscode';

export async function getVsCodeGitRoot(this: GitService): Promise<string | undefined> {
  try {
    const api = await this.getVsCodeGitApi();
    const rootUri = await api?.getRepositoryRoot(vscode.Uri.file(this.rootPath));
    return rootUri?.fsPath;
  } catch {
    return undefined;
  }
}
