// Generated by split-class.mjs
import type { GitService } from './index';

export async function resolveShaFilter(this: GitService, message: string): Promise<string | undefined> {
  const trimmed = message.trim();
  if (!/^[0-9a-f]{4,64}$/i.test(trimmed)) {
    return undefined;
  }
  try {
    const result = await this.runGit(['rev-parse', '--verify', `${trimmed}^{commit}`]);
    const sha = result.stdout.trim();
    return sha || undefined;
  } catch {
    return undefined;
  }
}
