// Generated by split-class.mjs
import type { GitService } from './index';

export async function resolveRecoveryCommit(
  this: GitService,
  oid: string
): Promise<string | undefined> {
  const candidate = oid.trim();
  if (!candidate) {
    return undefined;
  }

  try {
    const result = await this.runGitAllowExitCodes(['cat-file', '-t', candidate], [0, 128]);
    return result.stdout.trim() === 'commit' ? candidate : undefined;
  } catch {
    return undefined;
  }
}
