// Generated by split-class.mjs
import type { GitService } from './index';

export async function validateBranchName(
  this: GitService,
  name: string
): Promise<string | undefined> {
  const candidate = name.trim();
  if (!candidate) {
    return 'Branch name is required.';
  }
  if (candidate.startsWith('-')) {
    return 'Branch name cannot start with "-".';
  }

  try {
    await this.runGit(['check-ref-format', `refs/heads/${candidate}`]);
  } catch {
    return 'Invalid Git branch name.';
  }

  if (await this.refExists(`refs/heads/${candidate}`)) {
    return `Branch "${candidate}" already exists.`;
  }

  return undefined;
}
